Refactor pfetch and weather scripts

diff --git a/macOS/Users/cyan/bin/weather b/macOS/Users/cyan/bin/weather
--- a/macOS/Users/cyan/bin/weather
+++ b/macOS/Users/cyan/bin/weather
@@ -1,3 +1,16 @@
 #!/usr/bin/env sh
+
 CITY=""
-curl -s "https://wttr.in/$CITY?u&format=3" | sed 's/[^ ]* //' | sed 's/   +/ /'
+
+# Fetch the weather
+weather=$(curl -s -f "https://wttr.in/$CITY?u&format=3")
+
+if [ $? -eq 0 ]; then
+  # Response was successful, process it
+  echo "${weather}" | sed 's/[^ ]* //' | sed 's/ +/ /'
+elif [ -z "${CITY}" ]; then
+  # If CITY is empty
+  echo "City not specified, cannot fetch weather."
+else
+  echo "Unable to fetch weather data."
+fi
